#define VIAL_KEYBOARD_UID {0x77, 0x45, 0x64, 0x4A, 0xD6, 0x39, 0xAC, 0xBF}
#define VIAL_UNLOCK_COMBO_COLS { 0, 2 }
#define VIAL_UNLOCK_COMBO_ROWS { 0, 1}

#define VIAL_COMBO_ENTRIES 11
#define VIAL_TAP_DANCE_ENTRIES 15
#define DYNAMIC_KEYMAP_LAYER_COUNT 4

#define LAYER_STATE_8BIT